defmodule Valkka.Review do
  @moduledoc """
  Pure-function module for review state management.

  Identifies agent-attributed commits that need human review,
  tracks review progress. No process — callers hold state.
  Pattern follows `Valkka.Activity`.
  """

  alias Valkka.Cache.ReviewCache

  @agent_patterns [
    ~r/Co-Authored-By:\s*Claude/i,
    ~r/Co-Authored-By:\s*Cursor/i,
    ~r/Co-Authored-By:\s*Copilot/i,
    ~r/Generated by/i,
    ~r/🤖/
  ]

  @agent_authors ~w(claude aider copilot cursor devin windsurf)

  @doc """
  Check if a commit is agent-attributed based on message and author.
  """
  def agent_commit?(message, author) do
    message_match = Enum.any?(@agent_patterns, &Regex.match?(&1, message || ""))

    author_match =
      Enum.any?(@agent_authors, fn pattern ->
        String.contains?(String.downcase(author || ""), pattern)
      end)

    message_match or author_match
  end

  @doc """
  Given a list of commits (from git log), return those needing review.
  Filters to agent-attributed commits that haven't been marked reviewed.

  Commits should be maps with :oid, :message, :author fields.
  `ahead` limits how many recent commits to consider (ahead of remote).
  """
  def reviewable_commits(commits, repo_path, ahead \\ nil) do
    commits
    |> then(fn cs -> if ahead && ahead > 0, do: Enum.take(cs, ahead), else: cs end)
    |> Enum.filter(fn c ->
      agent_commit?(c.message, c.author) and not ReviewCache.reviewed?(repo_path, c.oid)
    end)
  end

  @doc "Mark a commit as reviewed."
  def mark_reviewed(repo_path, oid) do
    ReviewCache.mark_reviewed(repo_path, oid)
  end

  @doc "Check if a commit has been reviewed."
  def reviewed?(repo_path, oid) do
    ReviewCache.reviewed?(repo_path, oid)
  end

  @doc """
  Compute review summary for a repo.
  Returns %{total: N, reviewed: M, pending: P}.
  """
  def summary(commits, repo_path, ahead \\ nil) do
    candidates =
      commits
      |> then(fn cs -> if ahead && ahead > 0, do: Enum.take(cs, ahead), else: cs end)
      |> Enum.filter(fn c -> agent_commit?(c.message, c.author) end)

    reviewed = Enum.count(candidates, fn c -> ReviewCache.reviewed?(repo_path, c.oid) end)
    total = length(candidates)

    %{total: total, reviewed: reviewed, pending: total - reviewed}
  end
end
